---
title: "Recent Commit Activity"

format: html
subtitle: "This site automatically tracks a curated list of GitHub projects funded by NIH grant [R01CA230551](https://reporter.nih.gov/project-details/9963159) from the National Cancer Institute to Levi Waldron at the CUNY Graduate School of Public Health and Health Policy" 

toc: false
sidebar: false
---

### [`waldronlab/BugSigDBExports`](https://github.com/waldronlab/BugSigDBExports/commit/573f86337ecbe2ae0fc8a5a2e34286790846848f)

**Message:** Hourly export update

**Author:** GitHub Actions Bot

**Date:** 2025-08-11 14:08:21 UTC

---

### [`bd4everyone/MicrobiomeProject`](https://github.com/bd4everyone/MicrobiomeProject/commit/828ca0a1525a661249f3e53501f21f77f9a5be8c)

**Message:** Update index.qmd

**Author:** bd4everyone

**Date:** 2025-08-11 13:56:16 UTC

---

### [`bd4everyone/MicrobiomeProject`](https://github.com/bd4everyone/MicrobiomeProject/commit/e88c3a6f21a677e197cbc75f3c82127a5b6e3847)

**Message:** Update _quarto.yml

**Author:** bd4everyone

**Date:** 2025-08-11 13:47:07 UTC

---

### [`waldronlab/BugSigDBExports`](https://github.com/waldronlab/BugSigDBExports/commit/7db83ff2b8960d7470a454d306bcd899fe43412d)

**Message:** Hourly export update

**Author:** GitHub Actions Bot

**Date:** 2025-08-11 13:18:46 UTC

---

### [`waldronlab/BugSigDBExports`](https://github.com/waldronlab/BugSigDBExports/commit/f1d38453615743dd8052239222d9058df50cb9ed)

**Message:** Hourly export update

**Author:** GitHub Actions Bot

**Date:** 2025-08-11 12:06:01 UTC

---

### [`waldronlab/BugSigDBExports`](https://github.com/waldronlab/BugSigDBExports/commit/f9088bb81b5abd52587b7274b2450b41dec9e137)

**Message:** Hourly export update

**Author:** GitHub Actions Bot

**Date:** 2025-08-11 11:06:21 UTC

---

### [`waldronlab/BugSigDBExports`](https://github.com/waldronlab/BugSigDBExports/commit/e959db58795b6ed7b6f9ebb1bd71d176b237937a)

**Message:** Hourly export update

**Author:** GitHub Actions Bot

**Date:** 2025-08-11 10:06:13 UTC

---

### [`waldronlab/bugphyzzExports`](https://github.com/waldronlab/bugphyzzExports/commit/0b2bae419f86cc8a1d9933600f7bf7233d22d723)

**Message:** Update exports

**Author:** github-actions

**Date:** 2025-08-10 23:41:52 UTC

---

### [`bd4everyone/MicrobiomeProject`](https://github.com/bd4everyone/MicrobiomeProject/commit/d0027832f25c0f1efc3b17e2bbe5bdb0fc323879)

**Message:** Delete projects.qmd

**Author:** bd4everyone

**Date:** 2025-08-07 17:05:52 UTC

---

### [`bd4everyone/MicrobiomeProject`](https://github.com/bd4everyone/MicrobiomeProject/commit/18b1be19e8675dee2c3af7fb6010fbfc8838ff42)

**Message:** Delete commit_log.qmd

**Author:** bd4everyone

**Date:** 2025-08-07 17:05:14 UTC

---

### [`bd4everyone/MicrobiomeProject`](https://github.com/bd4everyone/MicrobiomeProject/commit/2446f09370b1a231964c89bd02624ea26a738c46)

**Message:** Add files via upload

**Author:** bd4everyone

**Date:** 2025-08-07 17:03:44 UTC

---

### [`waldronlab/BugSigDBStats`](https://github.com/waldronlab/BugSigDBStats/commit/42e820bd3a1ab14974273ab9f963da4998354b55)

**Message:** Merge pull request #19 from annemarie-sharp/improve-rmd-tables

**Author:** Chloe Mirzayi

**Date:** 2025-08-06 16:20:41 UTC

---

### [`waldronlab/bugphyzzExports`](https://github.com/waldronlab/bugphyzzExports/commit/34219d3ec8847790fff2b95f21dabd98efeefe15)

**Message:** Update exports

**Author:** github-actions

**Date:** 2025-08-03 23:44:06 UTC

---

### [`waldronlab/BugSigDBStats`](https://github.com/waldronlab/BugSigDBStats/commit/bf75e0a8e844b2e1dc10ba9bc7a779a56ffacc0b)

**Message:** Create nicer-looking tables in Rmd; update .gitignore and .Rbuildignore

**Author:** Anne-Marie Sharp

**Date:** 2025-08-01 19:46:26 UTC

---

### [`waldronlab/PublicMicrobiomeProject`](https://github.com/waldronlab/PublicMicrobiomeProject/commit/1885490acb0ea4a41b7f96e22b1257bcbfd6e7c4)

**Message:**  Link & icon (#2)

**Author:** bd4everyone

**Date:** 2025-07-31 14:26:32 UTC

---

### [`waldronlab/curatedMetagenomicDataAnalyses`](https://github.com/waldronlab/curatedMetagenomicDataAnalyses/commit/7b9a72dc470de4714f83c141cadccabe49762f9d)

**Message:** Minor comment in setup stage

**Author:** Giacomo Antonello

**Date:** 2025-07-30 14:43:10 UTC

---

### [`waldronlab/curatedMetagenomicDataAnalyses`](https://github.com/waldronlab/curatedMetagenomicDataAnalyses/commit/ae312cbc794c851e5f69bf77a05a8ca72fe93ca1)

**Message:** Update README.md with Zenodo badge

**Author:** Giacomo Antonello

**Date:** 2025-07-30 14:42:10 UTC

---

### [`waldronlab/curatedMetagenomicDataAnalyses`](https://github.com/waldronlab/curatedMetagenomicDataAnalyses/commit/089592d5b136c615ad2f1b4a9148c3144ee4e114)

**Message:** Major streamlining of git repository after paper re-submisison. Data are now on Zenodo, see https://doi.org/10.5281/zenodo.15856813

**Author:** Giacomo Antonello

**Date:** 2025-07-30 14:37:42 UTC

---

### [`waldronlab/curatedMetagenomicDataAnalyses`](https://github.com/waldronlab/curatedMetagenomicDataAnalyses/commit/82d7e377a4cc5ccf0b35f5469a4821e4d4f17e08)

**Message:** Merge branch 'main' of github.com:waldronlab/curatedMetagenomicDataAnalyses

**Author:** g-antonello

**Date:** 2025-07-30 09:53:31 UTC

---

### [`waldronlab/curatedMetagenomicDataAnalyses`](https://github.com/waldronlab/curatedMetagenomicDataAnalyses/commit/0f41bde0fc745b8a79c3857905a9f7595d9cc3c1)

**Message:** Added pre-set conda environment for quick install

**Author:** g-antonello

**Date:** 2025-07-30 09:52:46 UTC

---

### [`shbrief/curatedMetagenomicDataODM`](https://github.com/shbrief/curatedMetagenomicDataODM/commit/37df7650985db64f0e06b72728dab7909a391ce8)

**Message:** handling updated delimiter

**Author:** Sehyun Oh

**Date:** 2025-07-28 18:48:32 UTC

---

### [`waldronlab/bugphyzzExports`](https://github.com/waldronlab/bugphyzzExports/commit/e1a6f3923c82739e03fad6e0d9f0abfbf8817029)

**Message:** Update exports

**Author:** github-actions

**Date:** 2025-07-27 23:44:33 UTC

---

### [`shbrief/curatedMetagenomicDataODM`](https://github.com/shbrief/curatedMetagenomicDataODM/commit/ff26cc4cee4d37748f626a21c69a90aad484b624)

**Message:** update delimiter

**Author:** Sehyun Oh

**Date:** 2025-07-25 22:53:37 UTC

---

### [`waldronlab/curatedMetagenomicDataCuration`](https://github.com/waldronlab/curatedMetagenomicDataCuration/commit/5da05843c99a9e580d4271ef5a120d78332ef0b0)

**Message:** Merge pull request #102 from waldronlab/issue/99

**Author:** jwokaty

**Date:** 2025-07-22 19:53:52 UTC

---

### [`waldronlab/curatedMetagenomicDataCuration`](https://github.com/waldronlab/curatedMetagenomicDataCuration/commit/c69cb5e0778efddf3ea31b7278ff8fe4a4044c7e)

**Message:** Get last name

**Author:** A Wokaty

**Date:** 2025-07-22 19:32:29 UTC

---

### [`waldronlab/curatedMetagenomicDataCuration`](https://github.com/waldronlab/curatedMetagenomicDataCuration/commit/9989204daeda4bd04d0bdcd5abb15f51b4041a09)

**Message:** Push to default branch

**Author:** A Wokaty

**Date:** 2025-07-22 19:08:17 UTC

---

### [`waldronlab/curatedMetagenomicData`](https://github.com/waldronlab/curatedMetagenomicData/commit/e5b5f83fb46a28e61a25546bf0d70c2bc0e39d4d)

**Message:** Merge pull request #319 from shbrief/master

**Author:** Levi Waldron

**Date:** 2025-07-18 07:53:05 UTC

---

### [`waldronlab/curatedMetagenomicDataCuration`](https://github.com/waldronlab/curatedMetagenomicDataCuration/commit/987fefd09142e94dbf081e4b38020dd0bac84cba)

**Message:** Update cMD_doi.yml

**Author:** Sehyun Oh

**Date:** 2025-07-16 18:36:13 UTC

---

### [`waldronlab/curatedMetagenomicDataCuration`](https://github.com/waldronlab/curatedMetagenomicDataCuration/commit/c98c5708f56298f1dd09a5d4be9b484fbdf31e4d)

**Message:** Make BioProject as a required input for new study template

**Author:** Sehyun Oh

**Date:** 2025-07-14 17:09:11 UTC

---

### [`waldronlab/bugphyzzExports`](https://github.com/waldronlab/bugphyzzExports/commit/b83734496bb5a71ecd56edc82ffb450fc2a0ced1)

**Message:** Update exports

**Author:** github-actions

**Date:** 2025-07-13 23:43:29 UTC

---

### [`waldronlab/bugSigSimple`](https://github.com/waldronlab/bugSigSimple/commit/028352f0da94ae1a6315ad2ea189e1ab365b8987)

**Message:** Merge pull request #31 from annemarie-sharp/unittests-bugSigSimple

**Author:** Chloe Mirzayi

**Date:** 2025-07-10 21:46:13 UTC

---

### [`waldronlab/bugSigSimple`](https://github.com/waldronlab/bugSigSimple/commit/25a0e563b997f5d040c86a21418c71651ae73356)

**Message:** Add unit tests in testthat folder

**Author:** Anne-Marie Sharp

**Date:** 2025-07-10 15:08:13 UTC

---

### [`waldronlab/BugSigDB`](https://github.com/waldronlab/BugSigDB/commit/73b9399298f3f4f87f43f5a54ddc00890b042edf)

**Message:** Update cron image: ghcr.io/wikiteq/cron:20250709-2da693f (#272)

**Author:** Pavel Astakhov

**Date:** 2025-07-09 14:48:30 UTC

---

### [`waldronlab/BugSigDB`](https://github.com/waldronlab/BugSigDB/commit/9d24c6b300d14ad2f7dae852ad34d515de2c7704)

**Message:** Set --binlog_expire_logs_seconds=86400 (#271)

**Author:** Pavel Astakhov

**Date:** 2025-07-09 13:50:23 UTC

---

### [`waldronlab/bugphyzzExports`](https://github.com/waldronlab/bugphyzzExports/commit/787cf748d03fd5d43b3cae8b7ce17022a5bfd5c1)

**Message:** Update exports

**Author:** github-actions

**Date:** 2025-07-06 23:43:08 UTC

---

### [`waldronlab/PublicMicrobiomeProject`](https://github.com/waldronlab/PublicMicrobiomeProject/commit/ee242416315817fb8f32ae1acad43a0afdfae4b9)

**Message:** initial commit

**Author:** Levi Waldron

**Date:** 2025-07-06 21:03:02 UTC

---

### [`waldronlab/PublicMicrobiomeProject`](https://github.com/waldronlab/PublicMicrobiomeProject/commit/1b1a580ef4927393d0e83c157ccd1ee3f7873548)

**Message:** Initial commit

**Author:** Levi Waldron

**Date:** 2025-07-06 21:01:09 UTC

---

### [`waldronlab/BugSigDB`](https://github.com/waldronlab/BugSigDB/commit/f1e9ea3365ce05319fd7f4285aef7aeef5794eeb)

**Message:** Add mediawiki-ddos to varnish label (#270)

**Author:** Pavel Astakhov

**Date:** 2025-07-04 11:58:40 UTC

---

### [`waldronlab/BugSigDB`](https://github.com/waldronlab/BugSigDB/commit/5448ecb41bf4337a7042659de0f68894a98a0816)

**Message:** Update cron container (cron:20250704-10) (#269)

**Author:** Pavel Astakhov

**Date:** 2025-07-04 11:30:12 UTC

---

### [`waldronlab/BugSigDB`](https://github.com/waldronlab/BugSigDB/commit/8db4fe026d47ab5856ee5c135ecc8bf6bef7c938)

**Message:** Set PHP_MEMORY_LIMIT=2G to the matomo container (#267)

**Author:** Pavel Astakhov

**Date:** 2025-07-01 07:14:02 UTC

---

### [`waldronlab/taxPPro`](https://github.com/waldronlab/taxPPro/commit/c6d1fa560976b2475191d149d249a1dc0c9597c0)

**Message:** Add taxizedb, bump version to 1.0.1

**Author:** A Wokaty

**Date:** 2025-06-30 00:00:45 UTC

---

### [`seandavi/curatedMetagenomicsNextflow`](https://github.com/seandavi/curatedMetagenomicsNextflow/commit/4cde6fbcc090b67be78ba60e26330880a8d9c8eb)

**Message:** refactor pkl file munging

**Author:** Sean Davis

**Date:** 2025-06-25 20:46:59 UTC

---

### [`waldronlab/curatedMetagenomicData`](https://github.com/waldronlab/curatedMetagenomicData/commit/f383cef193325e3647de59b6477d1ac58570c653)

**Message:** Updates following the reviewer's suggestions

**Author:** Sehyun Oh

**Date:** 2025-06-06 03:31:59 UTC

---

### [`seandavi/curatedMetagenomicsNextflow`](https://github.com/seandavi/curatedMetagenomicsNextflow/commit/4bd6007ef767063385d999862c8507498161c67b)

**Message:** aws cli no longer a dependency

**Author:** Sean Davis

**Date:** 2025-06-03 15:34:31 UTC

---

### [`seandavi/curatedMetagenomicsNextflow`](https://github.com/seandavi/curatedMetagenomicsNextflow/commit/d88a87fbfb75f2ecd03ae8ec364ab0c27a346761)

**Message:** adds single-sample mode and kneaddata fixes

**Author:** Sean Davis

**Date:** 2025-06-03 15:07:29 UTC

---

### [`seandavi/curatedMetagenomicsNextflow`](https://github.com/seandavi/curatedMetagenomicsNextflow/commit/7434d16d55d804140d7891011191845d4fd85128)

**Message:** use newest container with metaphlan4.1.0

**Author:** Sean Davis

**Date:** 2025-06-03 14:11:06 UTC

---

### [`seandavi/curatedMetagenomicsNextflow`](https://github.com/seandavi/curatedMetagenomicsNextflow/commit/50d3f5bcb98264144bb7f322686cfee7116c7955)

**Message:** Merge pull request #25 from ASAP-MAC/main

**Author:** Sean Davis

**Date:** 2025-06-03 14:04:30 UTC

---

### [`waldronlab/bugsigdbr`](https://github.com/waldronlab/bugsigdbr/commit/864c8841684579973e5648082433ba0cd4b22f25)

**Message:** fix ontology test

**Author:** lgeistlinger

**Date:** 2025-05-29 16:59:55 UTC

---

### [`waldronlab/curatedMetagenomicData`](https://github.com/waldronlab/curatedMetagenomicData/commit/e77007c870ee42864dc6ab80e4eb54008eb0d303)

**Message:** version bump

**Author:** Sehyun Oh

**Date:** 2025-05-23 01:56:36 UTC

---

### [`waldronlab/curatedMetagenomicData`](https://github.com/waldronlab/curatedMetagenomicData/commit/5aa172ab2a91c45f52f9cc5a394d342eab960b29)

**Message:** add authors who updated the vignette

**Author:** Sehyun Oh

**Date:** 2025-05-23 01:56:20 UTC

---

### [`waldronlab/curatedMetagenomicData`](https://github.com/waldronlab/curatedMetagenomicData/commit/6613f06ffb88e3236e6c1ff5532120809ddae8b9)

**Message:** updated vignette

**Author:** Sehyun Oh

**Date:** 2025-05-22 19:34:39 UTC

---

### [`waldronlab/HMP16SData`](https://github.com/waldronlab/HMP16SData/commit/95b7a6d2005d3561f65af583ed4b70813ec4b8a4)

**Message:** version bump 1.29.1

**Author:** LiNk-NY

**Date:** 2025-05-05 21:58:46 UTC

---

### [`waldronlab/HMP16SData`](https://github.com/waldronlab/HMP16SData/commit/36dfc67b244cef6e510df62fb9a4c5b71fc494a2)

**Message:** add _pkgdown.yml and .github/workflows/pr_check.yml GHA

**Author:** LiNk-NY

**Date:** 2025-05-05 21:56:34 UTC

---

### [`waldronlab/bugSigSimple`](https://github.com/waldronlab/bugSigSimple/commit/c06a6067916762c228e0f0f541d7e34322749a55)

**Message:** Merge pull request #26 from waldronlab/16-update-student-vignettes-with-modern-analyses

**Author:** Chloe Mirzayi

**Date:** 2025-05-05 18:54:00 UTC

---

### [`waldronlab/bugsigdbr`](https://github.com/waldronlab/bugsigdbr/commit/905b02bd97c3a4265bf7e502ef7fa4bc8791ecc8)

**Message:** Bump version to 1.15.2

**Author:** J Wokaty

**Date:** 2025-04-24 05:07:24 UTC

---

### [`waldronlab/bugsigdbr`](https://github.com/waldronlab/bugsigdbr/commit/39fb50faa4c1b8cca222d5b99bbacb3bf50507cd)

**Message:** Update documentation

**Author:** J Wokaty

**Date:** 2025-04-24 05:07:03 UTC

---

### [`waldronlab/bugsigdbr`](https://github.com/waldronlab/bugsigdbr/commit/07326cbbe693c95c8f76fd35cebda028d3494233)

**Message:** Bump version to 1.15.1

**Author:** J Wokaty

**Date:** 2025-04-23 23:34:36 UTC

---

### [`waldronlab/bugsigdbr`](https://github.com/waldronlab/bugsigdbr/commit/604a171ab5f6d7dd8d8aa4fc34ce2e64a45b3c80)

**Message:** Update default to https://doi.org/10.5281/zenodo.15272273

**Author:** J Wokaty

**Date:** 2025-04-23 23:34:15 UTC

---

### [`waldronlab/BugSigDBStats`](https://github.com/waldronlab/BugSigDBStats/commit/544d8469d41c49d4d8571c87fce87daf49313d35)

**Message:** Turn off publication year until I can figure out how to make it work consistently.

**Author:** cmirzayi

**Date:** 2025-04-23 15:21:31 UTC

---

### [`waldronlab/BugSigDBStats`](https://github.com/waldronlab/BugSigDBStats/commit/4abb834a3382a123790e294543d13897d41fb865)

**Message:** Update pkgdown.yaml to use 3.21

**Author:** Chloe Mirzayi

**Date:** 2025-04-23 15:12:18 UTC

---

### [`waldronlab/lefser`](https://github.com/waldronlab/lefser/commit/0ac110dc526796d7b609532722b0e14452c0b838)

**Message:** version bump 1.19.1

**Author:** LiNk-NY

**Date:** 2025-04-22 20:33:11 UTC

---

### [`waldronlab/lefser`](https://github.com/waldronlab/lefser/commit/e3fd48ede0d45f94405982de16965ed39c84d5e0)

**Message:** update NEWS.md

**Author:** LiNk-NY

**Date:** 2025-04-22 20:33:03 UTC

---

### [`waldronlab/lefser`](https://github.com/waldronlab/lefser/commit/57ec0f8606b1e446d7d79c6b86cc8f7b01e7591a)

**Message:** document ellipsis in lefserClades

**Author:** LiNk-NY

**Date:** 2025-04-22 20:32:54 UTC

---

### [`waldronlab/lefser`](https://github.com/waldronlab/lefser/commit/07d2eb7f12eb4c2d1c37ae087a2a13d62f9f63f6)

**Message:** update R dependency to resolve build warning

**Author:** LiNk-NY

**Date:** 2025-04-22 19:56:38 UTC

---

### [`waldronlab/lefser`](https://github.com/waldronlab/lefser/commit/4f5d4ea53c082cb953213b3d7102216033c10d87)

**Message:** remove blockCol and groupCol from lefser

**Author:** LiNk-NY

**Date:** 2025-04-22 19:55:25 UTC

---

### [`waldronlab/MicrobiomeBenchmarkDataAnalyses`](https://github.com/waldronlab/MicrobiomeBenchmarkDataAnalyses/commit/0ddc5bef332dbde6c3e9f5442722a5df8c3efd40)

**Message:** Merge pull request #8 from cmirzayi/main

**Author:** Levi Waldron

**Date:** 2025-04-18 22:45:23 UTC

---

### [`waldronlab/MicrobiomeBenchmarkDataAnalyses`](https://github.com/waldronlab/MicrobiomeBenchmarkDataAnalyses/commit/1b2b32a25e94fa6949c2000b48e92b10f47a824b)

**Message:** Merge branch 'main' of https://github.com/cmirzayi/MicrobiomeBenchmarkDataAnalyses

**Author:** cmirzayi

**Date:** 2025-04-18 21:49:00 UTC

---

### [`waldronlab/MicrobiomeBenchmarkDataAnalyses`](https://github.com/waldronlab/MicrobiomeBenchmarkDataAnalyses/commit/ca61d6bf24b10e00ff1ffb8926b292b8cbfe5f55)

**Message:** Add enrichmentSummary HTML datatable

**Author:** cmirzayi

**Date:** 2025-04-18 21:48:58 UTC

---

### [`waldronlab/MicrobiomeBenchmarkDataAnalyses`](https://github.com/waldronlab/MicrobiomeBenchmarkDataAnalyses/commit/cdd29fd88c173a8e7df125eee42c2edea92401a4)

**Message:** Merge branch 'waldronlab:main' into main

**Author:** Chloe Mirzayi

**Date:** 2025-04-17 18:31:43 UTC

---

### [`waldronlab/MicrobiomeBenchmarkDataAnalyses`](https://github.com/waldronlab/MicrobiomeBenchmarkDataAnalyses/commit/6348fcdef4feb07ab0416b6f6b132c5cc1a0abab)

**Message:** fix legends to not be cut off

**Author:** cmirzayi

**Date:** 2025-04-17 18:31:21 UTC

---

### [`waldronlab/bugphyzz`](https://github.com/waldronlab/bugphyzz/commit/a40066658544eb812729fb4f0bbcc29efda4ae48)

**Message:** bump x.y.z version to odd y following creation of RELEASE_3_21 branch

**Author:** lshep

**Date:** 2025-04-15 14:24:32 UTC

---

### [`waldronlab/bugphyzz`](https://github.com/waldronlab/bugphyzz/commit/6e1b2a3fdb452ad8868f04b6d07612f1bb0506d7)

**Message:** bump x.y.z version to even y prior to creation of RELEASE_3_21 branch

**Author:** lshep

**Date:** 2025-04-15 14:24:32 UTC

---

### [`waldronlab/MicrobiomeBenchmarkData`](https://github.com/waldronlab/MicrobiomeBenchmarkData/commit/53e4667573c30c257f1828f3af4b252d5c0bb1a1)

**Message:** bump x.y.z version to odd y following creation of RELEASE_3_21 branch

**Author:** lshep

**Date:** 2025-04-15 14:23:01 UTC

---

### [`waldronlab/MicrobiomeBenchmarkData`](https://github.com/waldronlab/MicrobiomeBenchmarkData/commit/615e0573eaed0918fd2fa75ef5921556243ae0c7)

**Message:** bump x.y.z version to even y prior to creation of RELEASE_3_21 branch

**Author:** lshep

**Date:** 2025-04-15 14:23:01 UTC

---

### [`waldronlab/HMP16SData`](https://github.com/waldronlab/HMP16SData/commit/af66a1c42a2fd0896f9748ba2b7ac6644b9cb732)

**Message:** bump x.y.z version to odd y following creation of RELEASE_3_21 branch

**Author:** lshep

**Date:** 2025-04-15 14:10:08 UTC

---

### [`waldronlab/HMP16SData`](https://github.com/waldronlab/HMP16SData/commit/a58e99bb5263e78dc9a3c0bb437fbfe548b542ad)

**Message:** bump x.y.z version to even y prior to creation of RELEASE_3_21 branch

**Author:** lshep

**Date:** 2025-04-15 14:10:08 UTC

---

### [`waldronlab/BugSigDBcuration`](https://github.com/waldronlab/BugSigDBcuration/commit/c660273db16bc6621a2516d3a0ce8c7b1adc1996)

**Message:** Merge pull request #691 from waldronlab/fix-no-pmid

**Author:** jwokaty

**Date:** 2025-03-27 19:32:54 UTC

---

### [`waldronlab/BugSigDBcuration`](https://github.com/waldronlab/BugSigDBcuration/commit/a76d7d323a2e5f5986dce742db0602a5395cfa8c)

**Message:** If PMID not found, set as 'NA'

**Author:** J Wokaty

**Date:** 2025-03-27 19:25:52 UTC

---

### [`waldronlab/BugSigDBcuration`](https://github.com/waldronlab/BugSigDBcuration/commit/02f5d3b205ca888817a6e91554657a145d765749)

**Message:** Fix no PMID, doi link

**Author:** J Wokaty

**Date:** 2025-03-27 19:17:16 UTC

---

### [`waldronlab/bugSigSimple`](https://github.com/waldronlab/bugSigSimple/commit/70828b7a0519373da79ccdfacac57272cbb9fa04)

**Message:** Removed vignettes with older names

**Author:** Giacomo Antonello

**Date:** 2025-03-27 18:23:13 UTC

---

### [`waldronlab/bugSigSimple`](https://github.com/waldronlab/bugSigSimple/commit/719c0dd0002db8228122aaedca42b6daa74256cd)

**Message:** re-roxigenized and re-documented. R CMD check exited with 4 notes, no errors and no warnings

**Author:** Giacomo Antonello

**Date:** 2025-03-27 14:05:12 UTC

---

### [`waldronlab/BugSigDBcuration`](https://github.com/waldronlab/BugSigDBcuration/commit/3171dc9fa9070fb9281753dd9a81ed4a30643753)

**Message:** Merge pull request #686 from waldronlab/strip-html

**Author:** jwokaty

**Date:** 2025-03-25 20:09:01 UTC

---

### [`waldronlab/BugSigDBcuration`](https://github.com/waldronlab/BugSigDBcuration/commit/ae699eca7b2271f664a53ee8a38d42c9e008c994)

**Message:** Squish multiple spaces

**Author:** J Wokaty

**Date:** 2025-03-25 19:59:42 UTC

---

### [`shbrief/curatedMetagenomicDataODM`](https://github.com/shbrief/curatedMetagenomicDataODM/commit/e48c5a49175c30130d0bea43efc6ff6fbac3c85a)

**Message:** Update body_site_details

**Author:** krlong68

**Date:** 2025-03-18 20:02:13 UTC

---

### [`seandavi/nextflow_telemetry`](https://github.com/seandavi/nextflow_telemetry/commit/f8962a57d31ec7b318e1af2be523f09810edb325)

**Message:** Merge pull request #2 from IfeanyiSam/feature/containerization_optimization

**Author:** Sean Davis

**Date:** 2025-03-13 18:26:38 UTC

---

### [`seandavi/nextflow_telemetry`](https://github.com/seandavi/nextflow_telemetry/commit/013641c26c76e90e85e9abbe0a5c5181cfe031bd)

**Message:** feature: Nextflow API Process Optimization

**Author:** IfeanyiSam

**Date:** 2025-03-09 19:44:07 UTC

---

### [`shbrief/curatedMetagenomicDataODM`](https://github.com/shbrief/curatedMetagenomicDataODM/commit/96746a3d403dc846eb9794db0c3b9069b5d13931)

**Message:** Add dictionaries for "ancestry_details", "body_site_details", and "disease_details"; add Svetlana to curator list

**Author:** krlong68

**Date:** 2025-02-18 19:09:29 UTC

---

### [`shbrief/curatedMetagenomicDataODM`](https://github.com/shbrief/curatedMetagenomicDataODM/commit/c09d3eee3791a9319a001da8b87b5e7c6a430c7e)

**Message:** Add non-NCIT terms to "treatment" dictionary; create .owl files for "probing_pocket_depth", "smoker", and "feces_phenotype" terms

**Author:** krlong68

**Date:** 2025-02-07 13:12:20 UTC

---

### [`waldronlab/BugSigDBStats`](https://github.com/waldronlab/BugSigDBStats/commit/0031a5d3cd1da9016daa2433432d6d57bc2272fd)

**Message:** fixed sidebar and updated theme version

**Author:** cmirzayi

**Date:** 2025-02-06 17:05:43 UTC

---

### [`waldronlab/BugSigDBEnrich`](https://github.com/waldronlab/BugSigDBEnrich/commit/4312fc46fc13daf08fe341d7fb9e023f05246548)

**Message:** Add BM25 column to BugSigDBEnrich

**Author:** sdgamboa

**Date:** 2025-01-21 04:34:34 UTC

---

### [`waldronlab/BugSigDBEnrich`](https://github.com/waldronlab/BugSigDBEnrich/commit/76a594a127bf3603ff14cff0232cfcbaf38573c1)

**Message:** Add script with BM25

**Author:** sdgamboa

**Date:** 2025-01-09 22:49:36 UTC

---

### [`waldronlab/taxPPro`](https://github.com/waldronlab/taxPPro/commit/ebaac7f5bb28462d5386f91965791a0c030edb11)

**Message:** Merge branch 'main' of github.com:waldronlab/taxPPro

**Author:** sdgamboa

**Date:** 2025-01-06 19:39:37 UTC

---

### [`waldronlab/taxPPro`](https://github.com/waldronlab/taxPPro/commit/51b27dc2e3066499d377019d54ccb07de1af8b1e)

**Message:** Update pairwisedistances script

**Author:** sdgamboa

**Date:** 2025-01-06 19:39:17 UTC

---

### [`waldronlab/cMDMeta`](https://github.com/waldronlab/cMDMeta/commit/ca11848d0b38bcfe2947f593f565881b5243d26d)

**Message:** Clean code

**Author:** sdgamboa

**Date:** 2024-12-28 00:31:57 UTC

---

### [`waldronlab/cMDMeta`](https://github.com/waldronlab/cMDMeta/commit/b2c6f108d393c1609d56759f3ac8a5a2f6936894)

**Message:** Add shinydashbordPlus to imports

**Author:** sdgamboa

**Date:** 2024-12-27 05:23:23 UTC

---

### [`waldronlab/cMDMeta`](https://github.com/waldronlab/cMDMeta/commit/d955f71cd73ac899fd33cc0afd591d949260fe81)

**Message:** Refactor some of the functions and change function noame to launch the app

**Author:** sdgamboa

**Date:** 2024-12-26 22:41:29 UTC

---

### [`waldronlab/BugSigDBEnrich`](https://github.com/waldronlab/BugSigDBEnrich/commit/f78c74919b30ef4672a6ef333d24334a6af835b4)

**Message:** Add missing dependency, markdown, and write note when installing locally about having to confirm caching of BugSigDB data

**Author:** sdgamboa

**Date:** 2024-12-21 05:01:48 UTC

---

### [`waldronlab/BugSigDBEnrich`](https://github.com/waldronlab/BugSigDBEnrich/commit/865667e34c249c6b1f26aba3bba2feaef61e5cb1)

**Message:** Update help for selecting database

**Author:** sdgamboa

**Date:** 2024-12-20 22:09:54 UTC

---

### [`waldronlab/BugSigDBEnrich`](https://github.com/waldronlab/BugSigDBEnrich/commit/9453f0f11e3e018af250c04a1f16b1e71507c2eb)

**Message:** Change theme, update documentation, bump version, update instructions to try the app, how to run locally, bugphyzz dependency from bioc

**Author:** sdgamboa

**Date:** 2024-12-20 21:03:26 UTC

---

### [`waldronlab/cMDMeta`](https://github.com/waldronlab/cMDMeta/commit/58e8ff48779d16784810652f6b84c88f5372370f)

**Message:** Update README.md

**Author:** Samuel Gamboa

**Date:** 2024-12-11 02:29:50 UTC

---

### [`waldronlab/cMDMeta`](https://github.com/waldronlab/cMDMeta/commit/6de7859b775685d56fdc387c197bbb676940a3df)

**Message:** Update DESCRIPTION and README file

**Author:** sdgamboa

**Date:** 2024-12-11 02:27:26 UTC

---

### [`waldronlab/taxPPro`](https://github.com/waldronlab/taxPPro/commit/216f9b3f9d076e0c0d06ae2a207bc4ebf8592b01)

**Message:** Merge pull request #11 from jananiravi/main

**Author:** Samuel Gamboa

**Date:** 2024-11-21 18:14:41 UTC

---

### [`waldronlab/taxPPro`](https://github.com/waldronlab/taxPPro/commit/97e7eef925237b4009abf9dcad1b8707e1091ad5)

**Message:** Merge pull request #10 from jananiravi/patch-1

**Author:** Samuel Gamboa

**Date:** 2024-11-21 18:14:27 UTC

---

### [`shbrief/lefserBenchmarking`](https://github.com/shbrief/lefserBenchmarking/commit/0c83cecf4b06eed75adab7a56a8b967cb43530f9)

**Message:** update README

**Author:** Sehyun Oh

**Date:** 2024-11-19 14:51:28 UTC

---

### [`shbrief/lefserBenchmarking`](https://github.com/shbrief/lefserBenchmarking/commit/96db3224896e454621e88785f843b9c4f91bf456)

**Message:** minor updates

**Author:** Sehyun Oh

**Date:** 2024-11-19 14:51:15 UTC

---

### [`shbrief/lefserBenchmarking`](https://github.com/shbrief/lefserBenchmarking/commit/705befb99bdfde2d500ba267fd23acb822003c28)

**Message:** Supplementary Figure 2

**Author:** Sehyun Oh

**Date:** 2024-11-19 14:49:40 UTC

---

### [`shbrief/lefserBenchmarking`](https://github.com/shbrief/lefserBenchmarking/commit/3c49f01b177540b6ab36e99357636abfffd46c16)

**Message:** updated figures

**Author:** Sehyun Oh

**Date:** 2024-11-19 14:44:20 UTC

---

### [`waldronlab/bugphyzz`](https://github.com/waldronlab/bugphyzz/commit/3af6a514dd1cb1318216a3e0473d31f4ec9182f6)

**Message:** bump x.y.z version to odd y following creation of RELEASE_3_20 branch

**Author:** lshep

**Date:** 2024-10-29 13:55:47 UTC

---

### [`waldronlab/bugphyzz`](https://github.com/waldronlab/bugphyzz/commit/50358b07950e5ec37527e028cf0af22c1156c6c6)

**Message:** bump x.y.z version to even y prior to creation of RELEASE_3_20 branch

**Author:** lshep

**Date:** 2024-10-29 13:55:47 UTC

---

### [`waldronlab/MicrobiomeBenchmarkData`](https://github.com/waldronlab/MicrobiomeBenchmarkData/commit/d9e18a4e0dfe49146f345c5459ce5606320e43f0)

**Message:** bump x.y.z version to odd y following creation of RELEASE_3_20 branch

**Author:** lshep

**Date:** 2024-10-29 13:54:21 UTC

---

### [`waldronlab/MicrobiomeBenchmarkData`](https://github.com/waldronlab/MicrobiomeBenchmarkData/commit/d9e041552efc49ad7c06b502c75c16431c408045)

**Message:** bump x.y.z version to even y prior to creation of RELEASE_3_20 branch

**Author:** lshep

**Date:** 2024-10-29 13:54:21 UTC

---

### [`waldronlab/HMP16SData`](https://github.com/waldronlab/HMP16SData/commit/60c5af944022f955ae8ca96eb9d0bc95746b2897)

**Message:** bump x.y.z version to odd y following creation of RELEASE_3_20 branch

**Author:** lshep

**Date:** 2024-10-29 13:47:21 UTC

---

### [`waldronlab/bugphyzz`](https://github.com/waldronlab/bugphyzz/commit/6b04e5f412e60c20771382bce9f5deb19252b5fd)

**Message:** Update DESCRIPTION - remove taxize - bumbp version

**Author:** sdgamboa

**Date:** 2024-10-25 18:43:27 UTC

---

### [`shbrief/lefserBenchmarking`](https://github.com/shbrief/lefserBenchmarking/commit/9a7a292dc474aed46f00084f1e5f2dd567305dca)

**Message:** minor update in README

**Author:** Sehyun Oh

**Date:** 2024-10-06 03:09:00 UTC

---

### [`waldronlab/MicrobiomeBenchmarkDataLefse`](https://github.com/waldronlab/MicrobiomeBenchmarkDataLefse/commit/181c91ec166861a73d229f25419e5bce3fad2632)

**Message:** gingival data analysis for Fig2

**Author:** Sehyun Oh

**Date:** 2024-09-25 15:49:28 UTC

---

### [`waldronlab/MicrobiomeBenchmarkDataLefse`](https://github.com/waldronlab/MicrobiomeBenchmarkDataLefse/commit/bc4bea2e4b30dcd3a9de99c8d9696c438af85921)

**Message:** formatting update for the plots

**Author:** Sehyun Oh

**Date:** 2024-09-25 15:48:41 UTC

---

### [`waldronlab/MicrobiomeBenchmarkDataLefse`](https://github.com/waldronlab/MicrobiomeBenchmarkDataLefse/commit/a38f5099f278a2b568299c3f8f6f282583e5eeec)

**Message:** update plot labels

**Author:** Sehyun Oh

**Date:** 2024-09-20 18:43:20 UTC

---

### [`waldronlab/MicrobiomeBenchmarkDataLefse`](https://github.com/waldronlab/MicrobiomeBenchmarkDataLefse/commit/a52209717ef689e51e4c7a3ed50a6721cf1a9841)

**Message:** Add plots comparing lefses

**Author:** sdgamboa

**Date:** 2024-09-18 22:16:42 UTC

---

### [`waldronlab/MicrobiomeBenchmarkDataLefse`](https://github.com/waldronlab/MicrobiomeBenchmarkDataLefse/commit/258a7bfcecd310a732bff197f13aa1bf5cfbd60c)

**Message:** Add code for comparing lefse results

**Author:** sdgamboa

**Date:** 2024-09-18 15:38:11 UTC

---

### [`waldronlab/MicrobiomeBenchmarkData`](https://github.com/waldronlab/MicrobiomeBenchmarkData/commit/723cb97bb507b22c3737e5685c72a84d07e96918)

**Message:** Merge pull request #12 from waldronlab/sdgamboa/scml

**Author:** Samuel Gamboa

**Date:** 2024-09-02 23:13:45 UTC

---

### [`waldronlab/MicrobiomeBenchmarkDataPrep`](https://github.com/waldronlab/MicrobiomeBenchmarkDataPrep/commit/3389de0ca72d7b950292deb34f7f2ffab4f75c0f)

**Message:** Update README.md

**Author:** Samuel Gamboa

**Date:** 2024-09-02 17:42:07 UTC

---

### [`waldronlab/ncbitaxon`](https://github.com/waldronlab/ncbitaxon/commit/7df8d8e65a914e1b3c4022e9ba9409e6149a0041)

**Message:** Update README.md

**Author:** Samuel Gamboa

**Date:** 2024-08-21 15:11:13 UTC

---

### [`waldronlab/ncbitaxon`](https://github.com/waldronlab/ncbitaxon/commit/dd30b7fb0c56b7d2898ea692672efd518b0d6b0b)

**Message:** Update README.md

**Author:** Samuel Gamboa

**Date:** 2024-08-21 15:10:56 UTC

---

### [`waldronlab/ncbitaxon`](https://github.com/waldronlab/ncbitaxon/commit/eb722979c1a8b19d8a6dba839e6b098b7b2fff92)

**Message:** Update README.md

**Author:** Samuel Gamboa

**Date:** 2024-08-21 15:10:02 UTC

---

### [`waldronlab/ncbitaxon`](https://github.com/waldronlab/ncbitaxon/commit/bcecde73ddbc56f13067ddc244ddd4e746f8bec6)

**Message:** Update README.md

**Author:** Samuel Gamboa

**Date:** 2024-08-21 15:08:13 UTC

---

### [`waldronlab/ncbitaxon`](https://github.com/waldronlab/ncbitaxon/commit/901082455fb1b697d3861b7de17a4ed5e4c466ec)

**Message:** Update README

**Author:** sdgamboa

**Date:** 2024-08-20 19:54:21 UTC

---

### [`waldronlab/taxPProValidation`](https://github.com/waldronlab/taxPProValidation/commit/6ba9559146e0808a70f3ec152c0968451e31b8e7)

**Message:** update README - multistate

**Author:** sdgamboa

**Date:** 2024-07-05 20:23:39 UTC

---

### [`waldronlab/taxPProValidation`](https://github.com/waldronlab/taxPProValidation/commit/c54e059f4d085f334928304ef142514166f085a2)

**Message:** update README

**Author:** sdgamboa

**Date:** 2024-07-05 20:22:57 UTC

---

### [`waldronlab/taxPProValidation`](https://github.com/waldronlab/taxPProValidation/commit/893f394279c070ac368011cbd193d4f06408d2c5)

**Message:** Merge branch 'main' of github.com:waldronlab/taxPProValidation

**Author:** sdgamboa

**Date:** 2024-07-05 20:19:23 UTC

---

### [`waldronlab/taxPProValidation`](https://github.com/waldronlab/taxPProValidation/commit/cdb48ed9d0e331fff2c39b11934a5f8ce5066d80)

**Message:** Update README - binary

**Author:** sdgamboa

**Date:** 2024-07-05 20:19:03 UTC

---

### [`waldronlab/taxPProValidation`](https://github.com/waldronlab/taxPProValidation/commit/7c52cf27c990d86d243d9040bf1f6aece15a8c50)

**Message:** Update README.md

**Author:** Samuel D. Gamboa-Tuz

**Date:** 2024-07-05 20:18:39 UTC

---

### [`waldronlab/bugphyzzAnalyses`](https://github.com/waldronlab/bugphyzzAnalyses/commit/05c37dd004e5abea6aafe9c2c564f17af5613cec)

**Message:** update arguments and parameters in the makeSignatures calls

**Author:** sdgamboa

**Date:** 2024-06-28 20:31:53 UTC

---

### [`waldronlab/bugphyzzAnalyses`](https://github.com/waldronlab/bugphyzzAnalyses/commit/d8f8cf29dbe6d974b192332e06a88a8144b03cfd)

**Message:** Add table of ontology.

**Author:** sdgamboa

**Date:** 2024-06-11 02:58:44 UTC

---

### [`waldronlab/bugphyzzAnalyses`](https://github.com/waldronlab/bugphyzzAnalyses/commit/558397c3a331fbda99e5ab60252c243c0c7c1e6f)

**Message:** Update figure dimensions

**Author:** sdgamboa

**Date:** 2024-06-07 19:22:56 UTC

---

### [`waldronlab/bugphyzzAnalyses`](https://github.com/waldronlab/bugphyzzAnalyses/commit/658922eb39b12ff28cd3924bcf886e172b0a5d6f)

**Message:** Add symbols for significant levels to

**Author:** sdgamboa

**Date:** 2024-06-07 04:12:10 UTC

---

### [`waldronlab/bugphyzzAnalyses`](https://github.com/waldronlab/bugphyzzAnalyses/commit/ac215b65fa017d68b454768637b21af8522bc095)

**Message:** Add summary table for dbBact with P-value < 0.1.

**Author:** sdgamboa

**Date:** 2024-06-07 04:05:00 UTC

---

### [`seandavi/nextflow_telemetry`](https://github.com/seandavi/nextflow_telemetry/commit/151554d17febf83b36bbe559c65bd3e58c259dde)

**Message:** add config

**Author:** Sean Davis

**Date:** 2024-02-07 15:11:13 UTC

---

### [`seandavi/nextflow_telemetry`](https://github.com/seandavi/nextflow_telemetry/commit/4387c549aa011bdefaf64afa2ceb166b90360fe7)

**Message:** Dockerfile

**Author:** Sean Davis

**Date:** 2024-02-07 15:10:52 UTC

---

### [`seandavi/nextflow_telemetry`](https://github.com/seandavi/nextflow_telemetry/commit/3035409ba2929450448ec9837abd07ec93d2ed60)

**Message:** README

**Author:** Sean Davis

**Date:** 2024-02-07 15:10:30 UTC

---

### [`waldronlab/BugSigDBPaper`](https://github.com/waldronlab/BugSigDBPaper/commit/3b4c917ebeafe2b02a0fa689cfea5ca03a534b6c)

**Message:** Update README.md

**Author:** lgeistlinger

**Date:** 2023-10-19 15:37:53 UTC

---

### [`waldronlab/BugSigDBPaper`](https://github.com/waldronlab/BugSigDBPaper/commit/ec5f4a0acbfd356b3f5a3ab97468a8fb75a0999a)

**Message:** Update README.md

**Author:** lgeistlinger

**Date:** 2023-10-19 15:36:33 UTC

---

### [`waldronlab/BugSigDBPaper`](https://github.com/waldronlab/BugSigDBPaper/commit/fe7bebdd799ff94cb9531df901821237ded55036)

**Message:** Merge pull request #1 from waldronlab/lwaldron-patch-1

**Author:** lgeistlinger

**Date:** 2023-10-19 15:32:19 UTC

---

### [`waldronlab/BugSigDBPaper`](https://github.com/waldronlab/BugSigDBPaper/commit/df7c2b37b3dbe829bcd94f0b41c5c8429e9eb6d6)

**Message:** Update README.md

**Author:** Levi Waldron

**Date:** 2023-10-19 15:13:33 UTC

---

### [`waldronlab/BugSigDBPaper`](https://github.com/waldronlab/BugSigDBPaper/commit/69e919a5647d98aeef3b0d96872c33f836c865bc)

**Message:** Update README.md

**Author:** lgeistlinger

**Date:** 2023-09-12 21:02:42 UTC

---

### [`waldronlab/MicrobiomeBenchmarkDataPrep`](https://github.com/waldronlab/MicrobiomeBenchmarkDataPrep/commit/e73cad689095b6adee3e2d268fcab7e3d68ec7b9)

**Message:** Update README.md

**Author:** Samuel D. Gamboa-Tuz

**Date:** 2022-08-02 05:00:44 UTC

---

### [`waldronlab/MicrobiomeBenchmarkDataPrep`](https://github.com/waldronlab/MicrobiomeBenchmarkDataPrep/commit/d3852a230c00a2462b1c11a93e46f4bd24d60e20)

**Message:** correct typo healhy --> healthy

**Author:** sdgamboa

**Date:** 2022-07-07 13:26:47 UTC

---

### [`waldronlab/MicrobiomeBenchmarkDataPrep`](https://github.com/waldronlab/MicrobiomeBenchmarkDataPrep/commit/8d352345ece347ff24ffff48c3bb7b671074291d)

**Message:** Change library size of Sammler dataset back to raw counts.

**Author:** sdgamboa

**Date:** 2022-07-06 14:29:21 UTC

---

### [`waldronlab/MicrobiomeBenchmarkDataPrep`](https://github.com/waldronlab/MicrobiomeBenchmarkDataPrep/commit/a712427aa176415eb38ab173e16ae7e589032738)

**Message:** update script for counts of spike-in bacteria.

**Author:** sdgamboa

**Date:** 2022-07-06 00:16:38 UTC

---

### [`waldronlab/curatedMetagenomicDataShinyApp`](https://github.com/waldronlab/curatedMetagenomicDataShinyApp/commit/de27cab18f5572cd648ab036badbd579c18f9012)

**Message:** change repo/pkg name

**Author:** Samuel Gamboa

**Date:** 2021-11-29 14:33:52 UTC

---

### [`waldronlab/curatedMetagenomicDataShinyApp`](https://github.com/waldronlab/curatedMetagenomicDataShinyApp/commit/7ae2aa6a9d82dfee04637856977291800e241a70)

**Message:** update instructions for get_metadata

**Author:** Samuel Gamboa

**Date:** 2021-11-15 16:25:14 UTC

---

### [`waldronlab/curatedMetagenomicDataShinyApp`](https://github.com/waldronlab/curatedMetagenomicDataShinyApp/commit/9c8abeebbd067f211834d9969bf9f291ae45989d)

**Message:** add unlist SRRs

**Author:** Samuel Gamboa

**Date:** 2021-11-15 16:24:51 UTC

---

### [`waldronlab/curatedMetagenomicDataShinyApp`](https://github.com/waldronlab/curatedMetagenomicDataShinyApp/commit/81cc6d4867a2c8a1a5162daa3b61fd1659015074)

**Message:** update get_metadata output

**Author:** Samuel Gamboa

**Date:** 2021-11-15 14:44:54 UTC

---

### [`waldronlab/curatedMetagenomicDataShinyApp`](https://github.com/waldronlab/curatedMetagenomicDataShinyApp/commit/cf7897e9dd1b2b1e379d19e9d433ba1cf456d177)

**Message:** update documentation

**Author:** Samuel Gamboa

**Date:** 2021-11-15 04:38:07 UTC

---

### [`waldronlab/curatedMetagenomicDataTerminal`](https://github.com/waldronlab/curatedMetagenomicDataTerminal/commit/ec918d811ccaced0f1020609b079af3caed6cc5a)

**Message:** add windows instructions

**Author:** schifferl

**Date:** 2021-11-11 15:44:45 UTC

---

### [`waldronlab/curatedMetagenomicDataTerminal`](https://github.com/waldronlab/curatedMetagenomicDataTerminal/commit/7f9a5aea5108fa4d95ae7e72e14f23764144c2c2)

**Message:** merge #11 (cmirzayi/main)

**Author:** Lucas Schiffer

**Date:** 2021-11-11 15:27:59 UTC

---

### [`waldronlab/curatedMetagenomicDataTerminal`](https://github.com/waldronlab/curatedMetagenomicDataTerminal/commit/dbca82189af77653ad164c40c33519624399dedc)

**Message:** Add Windows instructions to README.Rmd

**Author:** Chloe Mirzayi

**Date:** 2021-11-04 21:39:24 UTC

---

### [`waldronlab/curatedMetagenomicDataPipeline`](https://github.com/waldronlab/curatedMetagenomicDataPipeline/commit/bdc03f235c04a0d476f0ecc33093f166843cf189)

**Message:** switch to dgCMatrix

**Author:** schifferl

**Date:** 2021-10-13 18:05:47 UTC

---

### [`waldronlab/curatedMetagenomicDataTerminal`](https://github.com/waldronlab/curatedMetagenomicDataTerminal/commit/45c4d4e8bc8c623fdd4977db24776a1cb4c927eb)

**Message:** use tinyurl link

**Author:** schifferl

**Date:** 2021-10-13 15:57:56 UTC

---

### [`waldronlab/curatedMetagenomicDataTerminal`](https://github.com/waldronlab/curatedMetagenomicDataTerminal/commit/a31d96eddb419231585a12681261cfb4065f0aed)

**Message:** Merge pull request #9 from waldronlab/schifferl

**Author:** Lucas Schiffer

**Date:** 2021-10-13 15:44:26 UTC

---

### [`waldronlab/curatedMetagenomicDataPipeline`](https://github.com/waldronlab/curatedMetagenomicDataPipeline/commit/2b5f05b6120ea1275213acd64c7248620ee5099d)

**Message:** update make_csv function

**Author:** schifferl

**Date:** 2021-04-09 20:31:18 UTC

---

### [`waldronlab/curatedMetagenomicDataPipeline`](https://github.com/waldronlab/curatedMetagenomicDataPipeline/commit/345757987584f819ca573ef8478e3d4342978434)

**Message:** update make_csv function

**Author:** schifferl

**Date:** 2021-04-06 11:21:34 UTC

---

### [`waldronlab/curatedMetagenomicDataPipeline`](https://github.com/waldronlab/curatedMetagenomicDataPipeline/commit/4235c479fffec501f855de935e5e536e39dc0af1)

**Message:** add make_csv function

**Author:** schifferl

**Date:** 2021-04-05 20:58:15 UTC

---

### [`waldronlab/curatedMetagenomicDataPipeline`](https://github.com/waldronlab/curatedMetagenomicDataPipeline/commit/4b69c4f01b3604dfa39dd03aa0071e7f306ecac9)

**Message:** add save_rda function

**Author:** schifferl

**Date:** 2021-03-31 02:11:57 UTC

---

### [`waldronlab/MicrobiomeWorkshop`](https://github.com/waldronlab/MicrobiomeWorkshop/commit/f31fe45ce8788a9e1b9ee473ee1b65457eebc428)

**Message:** Almost final version

**Author:** Ekaterina Smirnova

**Date:** 2019-06-20 13:58:05 UTC

---

### [`waldronlab/MicrobiomeWorkshop`](https://github.com/waldronlab/MicrobiomeWorkshop/commit/ed5af78a924ac03553353b532d2b8f1f770d4fba)

**Message:** further updates

**Author:** Ekaterina Smirnova

**Date:** 2019-06-19 21:20:58 UTC

---

### [`waldronlab/MicrobiomeWorkshop`](https://github.com/waldronlab/MicrobiomeWorkshop/commit/ff612ec153d3363888d353f74064c1f409a3f441)

**Message:** updated text and figures

**Author:** Ekaterina Smirnova

**Date:** 2019-06-19 17:03:26 UTC

---

### [`waldronlab/MicrobiomeWorkshop`](https://github.com/waldronlab/MicrobiomeWorkshop/commit/a7cc1d2636a21a973ca2d65a2b6202c4c9a3e032)

**Message:** text updates

**Author:** Ekaterina Smirnova

**Date:** 2019-06-19 14:03:51 UTC

---

### [`waldronlab/MicrobiomeWorkshop`](https://github.com/waldronlab/MicrobiomeWorkshop/commit/336d541980de6913ba6338f0028fa5a553bdb372)

**Message:** Add Imports, fixes #9

**Author:** Levi Waldron

**Date:** 2019-06-12 18:50:29 UTC

---

