---
title : "Exploiting Public Metagenomic Data to Uncover Cancer-Microbiome Relationships"
---

This site automatically tracks GitHub repositories associated with NCI grant [R01CA230551](https://reporter.nih.gov/project-details/10990882) to the CUNY Graduate School of Public Health and Health Policy.

* PI: [Levi Waldron](https://scholar.google.com/citations?user=-Bfm-2IAAAAJ&hl=en&oi=ao)
* co-Investigators: [Curtis Huttenhower](https://scholar.google.com/citations?user=yFncM6AAAAAJ&hl=en&oi=ao), [Nicola Segata](https://scholar.google.com/citations?user=ZXjO-Q4AAAAJ&hl=en&oi=ao), [Sean Davis](https://scholar.google.com/citations?user=hLFc29kAAAAJ&hl=en&oi=ao)

## Navigation

* **[Overview](./overview.html)**: Project abstract.

* **[Projects](./projects.html)**: A table of all repositories found for the tracked topic.

* **[Recent Commits](./commit_log.html)**: A blog-style feed of the latest commits from all listed projects.

## Public Health Relevance

The human microbiome is implicated in the development and response to treatment of some cancers, including infectious agents estimated to be responsible for ~20% of the global cancer burden. However, previously unrecognized bacterial and viral strains, as well as loss of normal structure and function of human-associated microbiomes, likely play additional roles in disease etiology and treatment. This project investigates the role of the human microbiome in cancer by applying novel and state-of-the-art methods to published metagenomic data, and provides enhanced, expanded, and more efficiently usable microbiome data resources back to the cancer research community for a broad range of investigations.
