---
title: "Overview of the 'Public Microbiome Project'"
---

Full title: **Exploiting Public Metagenomic Data to Uncover Cancer-Microbiome Relationships**

## Abstract

Dysbiosis of the host microbiome is now recognized as a hallmark of cancer and a factor in the systemic response to immunotherapy. While a large volume of literature and data resources on microbiome research are available, systemic comparison and analysis are limited due to the heterogeneity in data and reporting schema. To enable rapid and cost-effective elucidation of the roles of microorganisms in the etiology and progression of cancer, we have developed high-quality harmonized databases of public microbiome data and microbial signatures. This proposal expands and creates new features of these microbiome databases through four aims. First, it will enhance the analytic scope of BugSigDB, a Semantic Mediawiki for manual curation and review of microbial signatures by incorporating microbial physiologies and morphologies, predicted metabolic functions, automatic identification of similar signatures, and creation of user-friendly Bug Set Enrichment Analysis workflows. Second, it will establish the next generation of curatedMetagenomicData, a microbiome database of large-scale manual curation and uniformly processed shotgun sequencing data, supporting [FAIR](https://datascience.nih.gov/data-ecosystem) principles. We will create a federated, ontology-based curation system and distributed computing metagenomic profiling workflow, both applicable to all Sequence Read Archive (SRA) records. Third, it will expand curatedMetagenomicData and BugSigDB with data from thousands of published studies and perform meta-analyses using these resources. Lastly, we will mobilize hundreds of data curators from diverse backgrounds by participating in established internship programs and mobilize the microbiome research community to adopt reporting standards for publication. This contribution is significant because it increases the likelihood of developing effective public health interventions to prevent and detect microbiota-linked cancers by providing methods for improved mechanistic interpretation of microbiome studies, extracting new information from published raw metagenomic shotgun sequencing data and metadata, and enabling re-use of existing data by a much broader range of researchers and methodologies. The proposed research is innovative because it identifies and corrects important deficiencies in how microbiome data are published, increasing the utility of public data and published results on a large scale by other research teams.
